# Generated by Django 5.2 on 2025-11-29 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_movimientoinventario_producto_codigo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimientoinventario',
            name='producto_pk',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
