# Generated by Django 5.2 on 2025-11-29 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_movimientoinventario_producto_pk'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movimientoinventario',
            name='producto_pk',
        ),
    ]
