# Generated by Django 5.2 on 2025-11-29 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_movimientoinventario_producto_pk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimientoinventario',
            name='tipo',
            field=models.CharField(choices=[('ALTA', 'Alta'), ('BAJA', 'Baja'), ('MODI', 'Modificación')], max_length=8),
        ),
    ]
