# Generated by Django 5.2 on 2025-11-29 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_movimientoinventario_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimientoinventario',
            name='resumen_operacion',
            field=models.TextField(blank=True),
        ),
    ]
