# Generated by Django 5.2 on 2025-11-29 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_movimientoinventario_resumen_operacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimientoinventario',
            name='resumen_operacion',
            field=models.TextField(blank=True, null=True),
        ),
    ]
